### ISSUE TITLE
Issues using MariaDB Jupyter Kernel in Ubuntu 20.04 (no virtual machine)

### ISSUE THREAD

**Issue by JoanLamprea** [MariaDB/mariadb_kernel#37]
Hi, comunity! 

**I've been trying to instal and to execute the MariaDB Kernel's code because it is imperative for the class I am enrolled in. It happens that I do the process that is in this page and at the moment of executing Jupyter-Lab, I get the errors that I attach below. Additionally, I show you the code I use to do the process. 
I would appreciate any help you could give me.**

`(base) joan@joan-IdeaPad-3-15ALC6:~$ cd Descagas
bash: cd: Descagas: No existe el archivo o el directorio
(base) joan@joan-IdeaPad-3-15ALC6:~$ cd Descargas
(base) joan@joan-IdeaPad-3-15ALC6:~/Descargas$ conda activate maria_env
(maria_env) joan@joan-IdeaPad-3-15ALC6:~/Descargas$ python3 -m pip install mariadb_kernel
Requirement already satisfied: mariadb_kernel in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (0.2.0)
Requirement already satisfied: beautifulsoup4 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (4.10.0)
Requirement already satisfied: json2html in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (1.3.0)
Requirement already satisfied: mycli in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (1.24.3)
Requirement already satisfied: matplotlib in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (3.5.1)
Requirement already satisfied: pandas in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (1.3.5)
Requirement already satisfied: ipykernel in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (5.5.5)
Requirement already satisfied: lxml in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (4.8.0)
Requirement already satisfied: setuptools-scm in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (6.4.2)
Requirement already satisfied: setuptools in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mariadb_kernel) (58.0.4)
Requirement already satisfied: soupsieve>1.2 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from beautifulsoup4->mariadb_kernel) (2.3.1)
Requirement already satisfied: traitlets>=4.1.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipykernel->mariadb_kernel) (5.1.1)
Requirement already satisfied: ipython>=5.0.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipykernel->mariadb_kernel) (7.31.1)
Requirement already satisfied: jupyter-client in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipykernel->mariadb_kernel) (7.1.2)
Requirement already satisfied: tornado>=4.2 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipykernel->mariadb_kernel) (6.1)
Requirement already satisfied: decorator in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (5.1.1)
Requirement already satisfied: backcall in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (0.2.0)
Requirement already satisfied: jedi>=0.16 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (0.18.1)
Requirement already satisfied: matplotlib-inline in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (0.1.3)
Requirement already satisfied: pexpect>4.3 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (4.8.0)
Requirement already satisfied: pickleshare in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (0.7.5)
Requirement already satisfied: pygments in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (2.11.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from ipython>=5.0.0->ipykernel->mariadb_kernel) (3.0.27)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from jedi>=0.16->ipython>=5.0.0->ipykernel->mariadb_kernel) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from pexpect>4.3->ipython>=5.0.0->ipykernel->mariadb_kernel) (0.7.0)
Requirement already satisfied: wcwidth in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->mariadb_kernel) (0.2.5)
Requirement already satisfied: nest-asyncio>=1.5 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from jupyter-client->ipykernel->mariadb_kernel) (1.5.4)
Requirement already satisfied: entrypoints in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from jupyter-client->ipykernel->mariadb_kernel) (0.4)
Requirement already satisfied: python-dateutil>=2.1 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from jupyter-client->ipykernel->mariadb_kernel) (2.8.2)
Requirement already satisfied: pyzmq>=13 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from jupyter-client->ipykernel->mariadb_kernel) (19.0.2)
Requirement already satisfied: jupyter-core>=4.6.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from jupyter-client->ipykernel->mariadb_kernel) (4.9.2)
Requirement already satisfied: six>=1.5 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from python-dateutil>=2.1->jupyter-client->ipykernel->mariadb_kernel) (1.16.0)
Requirement already satisfied: cycler>=0.10 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from matplotlib->mariadb_kernel) (0.11.0)
Requirement already satisfied: numpy>=1.17 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from matplotlib->mariadb_kernel) (1.21.5)
Requirement already satisfied: fonttools>=4.22.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from matplotlib->mariadb_kernel) (4.29.1)
Requirement already satisfied: packaging>=20.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from matplotlib->mariadb_kernel) (21.3)
Requirement already satisfied: pillow>=6.2.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from matplotlib->mariadb_kernel) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from matplotlib->mariadb_kernel) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from matplotlib->mariadb_kernel) (1.3.2)
Requirement already satisfied: pyaes>=1.6.1 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (1.6.1)
Requirement already satisfied: click>=7.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (8.0.4)
Requirement already satisfied: cryptography>=1.0.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (35.0.0)
Requirement already satisfied: PyMySQL>=0.9.2 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (1.0.2)
Requirement already satisfied: sqlparse<0.5.0,>=0.3.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (0.4.2)
Requirement already satisfied: pyperclip>=1.8.1 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (1.8.2)
Requirement already satisfied: configobj>=5.0.5 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (5.0.6)
Requirement already satisfied: cli-helpers[styles]>=2.2.1 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from mycli->mariadb_kernel) (2.2.1)
Requirement already satisfied: tabulate[widechars]>=0.8.2 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from cli-helpers[styles]>=2.2.1->mycli->mariadb_kernel) (0.8.9)
Requirement already satisfied: importlib-metadata in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from click>=7.0->mycli->mariadb_kernel) (4.11.1)
Requirement already satisfied: cffi>=1.12 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from cryptography>=1.0.0->mycli->mariadb_kernel) (1.15.0)
Requirement already satisfied: pycparser in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from cffi>=1.12->cryptography>=1.0.0->mycli->mariadb_kernel) (2.21)
Requirement already satisfied: typing-extensions>=3.6.4 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from importlib-metadata->click>=7.0->mycli->mariadb_kernel) (4.1.1)
Requirement already satisfied: zipp>=0.5 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from importlib-metadata->click>=7.0->mycli->mariadb_kernel) (3.7.0)
Requirement already satisfied: pytz>=2017.3 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from pandas->mariadb_kernel) (2021.3)
Requirement already satisfied: tomli>=1.0.0 in ./sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages (from setuptools-scm->mariadb_kernel) (2.0.1)
(maria_env) joan@joan-IdeaPad-3-15ALC6:~/Descargas$ 
(maria_env) joan@joan-IdeaPad-3-15ALC6:~/Descargas$ python3 -m mariadb_kernel.install
Installing Jupyter kernel spec

(maria_env) joan@joan-IdeaPad-3-15ALC6:~/Descargas$ 
(maria_env) joan@joan-IdeaPad-3-15ALC6:~/Descargas$ 
(maria_env) joan@joan-IdeaPad-3-15ALC6:~/Descargas$ jupyter-lab
[I 2022-02-27 11:25:44.186 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-02-27 11:25:44.323 ServerApp] nbclassic | extension was successfully linked.
[I 2022-02-27 11:25:44.347 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-02-27 11:25:44.348 LabApp] JupyterLab extension loaded from /home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/jupyterlab
[I 2022-02-27 11:25:44.348 LabApp] JupyterLab application directory is /home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/share/jupyter/lab
[I 2022-02-27 11:25:44.351 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-02-27 11:25:44.352 ServerApp] Serving notebooks from local directory: /home/joan/Descargas
[I 2022-02-27 11:25:44.352 ServerApp] Jupyter Server 1.13.5 is running at:
[I 2022-02-27 11:25:44.352 ServerApp] http://localhost:8888/lab?token=d2aab2884874d44032e8216f02ff81f1963936b2dd9dcd0f
[I 2022-02-27 11:25:44.352 ServerApp]  or http://127.0.0.1:8888/lab?token=d2aab2884874d44032e8216f02ff81f1963936b2dd9dcd0f
[I 2022-02-27 11:25:44.352 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-02-27 11:25:44.397 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/joan/.local/share/jupyter/runtime/jpserver-6074-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=d2aab2884874d44032e8216f02ff81f1963936b2dd9dcd0f
     or http://127.0.0.1:8888/lab?token=d2aab2884874d44032e8216f02ff81f1963936b2dd9dcd0f
[W 2022-02-27 11:25:48.527 LabApp] Could not determine jupyterlab build status without nodejs
[W 2022-02-27 11:25:49.098 ServerApp] Notebook Untitled.ipynb is not trusted
[I 2022-02-27 11:25:49.316 ServerApp] Kernel started: 6d5244c6-e2a6-48a0-8bc8-4ac9dab71679
**[IPKernelApp] ERROR | MariaDB client failed to start
[IPKernelApp] ERROR | Most probably the MariaDB server is not started
[IPKernelApp] ERROR | No MariaDB Server found at /usr/bin/mariadbd;
[IPKernelApp] ERROR | Please install MariaDB from mariadb.org/download
[IPKernelApp] ERROR | If this is on purpose, you are limited to connecting to remote databases only
[IPKernelApp] Starting a client connection used in code completion
[IPKernelApp] ERROR | MariaDB client failed to start
[IPKernelApp] ERROR | Most probably the MariaDB server is not started
[IPKernelApp] ERROR | Code completion functionalities were disabled due to an unexpected error**
[W 2022-02-27 11:25:53.227 ServerApp] Got events for closed stream None
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 538, in execute_request
    user_expressions, allow_stdin,
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/mariadb_kernel/kernel.py", line 129, in do_execute
    result = self.mariadb_client.run_statement(s)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/mariadb_kernel/mariadb_client.py", line 108, in run_statement
    result = self.maria_repl.run_command(code, timeout)
AttributeError: 'NoneType' object has no attribute 'run_command'
[I 2022-02-27 11:26:29.851 ServerApp] Starting buffering for 6d5244c6-e2a6-48a0-8bc8-4ac9dab71679:f9301cc5-18cf-411d-b285-aeb3e5ed4d09
[I 2022-02-27 11:26:29.868 ServerApp] Starting buffering for 6d5244c6-e2a6-48a0-8bc8-4ac9dab71679:0830b157-7c86-4b79-a278-ce151f1d680f
[I 2022-02-27 11:26:29.872 ServerApp] Discarding 3 buffered messages for 6d5244c6-e2a6-48a0-8bc8-4ac9dab71679:0830b157-7c86-4b79-a278-ce151f1d680f
[E 2022-02-27 11:26:29.879 ServerApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
        callback(*args, **kwargs)
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 203, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/jupyter_server/services/kernels/handlers.py", line 534, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/jupyter_server/base/zmqhandlers.py", line 301, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2022-02-27 11:26:29.883 ServerApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
        self._handle_recv()
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
        callback(*args, **kwargs)
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 203, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/jupyter_server/services/kernels/handlers.py", line 534, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/jupyter_server/base/zmqhandlers.py", line 301, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(23, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(23, 1)>
Traceback (most recent call last):
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 462, in _handle_events
    self._handle_recv()
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _run_callback
    callback(*args, **kwargs)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 203, in <lambda>
    self.on_recv(lambda msg: callback(self, msg), copy=copy)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/jupyter_server/services/kernels/handlers.py", line 534, in _on_zmq_reply
    super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/jupyter_server/base/zmqhandlers.py", line 301, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
[I 2022-02-27 11:26:29.885 ServerApp] Starting buffering for 6d5244c6-e2a6-48a0-8bc8-4ac9dab71679:f9301cc5-18cf-411d-b285-aeb3e5ed4d09
[W 2022-02-27 11:26:31.273 LabApp] Could not determine jupyterlab build status without nodejs
[W 2022-02-27 11:26:31.828 ServerApp] Notebook Untitled.ipynb is not trusted
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 538, in execute_request
    user_expressions, allow_stdin,
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/mariadb_kernel/kernel.py", line 129, in do_execute
    result = self.mariadb_client.run_statement(s)
  File "/home/joan/Descargas/sudo/home/pi/miniconda3/envs/maria_env/lib/python3.7/site-packages/mariadb_kernel/mariadb_client.py", line 108, in run_statement
    result = self.maria_repl.run_command(code, timeout)
AttributeError: 'NoneType' object has no attribute 'run_command'
![error 1](https://user-images.githubusercontent.com/89352304/155891049-807ec203-251f-4c0f-9216-feaf3c58e5b4.png)
![error 2](https://user-images.githubusercontent.com/89352304/155891051-f5fd785b-b881-4f9f-9fac-c70eb994d83c.png)
`

**Comment by sunxiaoguang** [comment]
Looks like client couldn't connect to a MariaDB server.  I had similar issue earlier, and figured out there could be multiple reasons for that and here is a list of some of them.

* didn't install mariadb-client and mariadb-server packages
* have a ~/.jupyter/mariadb_config.json file but the configuration is incorrect somehow 
* connecting to Oracle distribution of MySQL server instead of MariaDB server. 

Of cause there could be more reasons, but hope these hints help.

**Comment by sunxiaoguang** [comment]
BTW: I have created a [PR](#40 ) to make it possible to connect to other MySQL compatible servers.
Add an extra config item to ~/.jupyter/mariadb_config.json like this will make it work
{
    "server_name": "MySQL"
}

**Comment by LinuxJedi** [comment]
I'm going to close this one for now. But if you have any more issues regarding this please feel free to reopen.
